#!/bin/bash
# 9. From the shell of a debian container, install via the container’s package
# manager everything you need to compile C source code and push it onto a git 
# repo (of course, make sure before that the package manager and the packages 
# already in the container are updated). For this exercise, you should only 
# specify the commands to be run directly in the container. 
# 1 Start debian container

docker run -t-i --rm debian
docker run -it debian /bin/bash

### --rm  Automatically remove the container when it exits
# 2  Install what you need to compile C

apt-get update
apt-get upgrade -y
apt-get install -y build-essential

# 3 Install git to push the source code

apt-get install git -y
