#!/bin/bash
# 15. Launch a phpmyadmin container as a background task. It should be named 
# roach-warden, its 80 port should be bound to the 8081 port of the virtual
# machine and it should be able to explore the database stored in the 
# spawning-pool container.

# docker run --name roach-warden  -d --link spawning-pool:db -p 8081:80 phpmyadmin/phpmyadmin

docker container run --name roach-warden -d -p 8081:80 --link spawning-pool:zerglings -e PMA_PASSWORD=Kerrigan -e PMA_HOST=spawning-pool phpmyadmin/phpmyadmin

## To test it you can put your ip and the por on your browser, like:
# http://192.168.99.100:8081/
# or http://0.0.0.0:8081
