#!/bin/bash
# 19. Launch a container name Abathur. It will be a Python container, 2-slim 
# version, its /root folder will be bound to a HOME folder on your host, and 
# its 3000 port will be bound to the 3000 port of your virtual machine. You 
# will personalize this container so that you can use the Flask micro-framework
# in its latest version. You will make sure that an html page displaying "Hello 
# World" with <h1> tags can be served by Flask. You will test that your 
# container is properly set up by accessing, via curl or a web browser, the IP
# address of your virtual machine on the 3000 port. You will also list all the
# necessary commands in your repository.


#install python and binded mount on ~
docker run --name Abathur -v /Users/tavelino/Abathur:/root -p 3000:3000 -dit python:2-slim

#install flask on the python container
docker exec Abathur pip install Flask

# create script hello world
echo 'from flask import Flask\napp = Flask(__name__)\n@app.route("/")\ndef hello_world():\n\treturn "<h1>[= Hello, World! =]</h1>"' > ~/Abathur/app.py
#echo 'from flask import Flask\napp = Flask(__name__)\n@app.route("/")\ndef hello_world():\n\treturn "<h1>Hello, World!</h1>"' > ~/app.py

docker exec -e FLASK_APP=/root/app.py Abathur flask run --host=0.0.0.0 --port 3000

## To check if its running 
# curl $(docker-machine ip Char):3000
# or curl 127.0.0.1:3000
# works on browser too.
