#!/bin/bash
# 21. Create another virtual machine with docker-machine using the virtualbox
# driver, and name it Aiur.
 
 docker-machine create --driver virtualbox Aiur

## To see your nodes
#docker-machine ls
################################
## understanding create command:
## docker-machine create --driver <driver> <machine name>
## aqui a gente cria uma nova maquina que se comunica com o gerenciador.

