#!/bin/bash
# 27. Get the real-time logs of one the tasks of the engineering-bay service.

docker service logs -f $(docker service ps engineering-bay -f 
"name=engineering-bay.1" -q)

#############################################################################
# source: https://docs.docker.com/engine/reference/commandline/service_ps/
# you can filter using your tasks names
